settings:
  message-prefix: "&6[Profession]&r "
  debug-mode: true

messages:
  no-permission: "You do not have permission to use this command."
  unknown-command: "Unknown command. Use {command} help for a list of commands."
  help-message:
    choose: "Choose your profession."
    info: "Get information about your current profession."
    list: "List all available professions."
    reset: "Reset your current profession."
  profession-info:
    header: "Profession Info"
    no-profession: "You do not have a profession selected."
    current: "Current Profession"
    description-header: "Description"
    allowed-tools-header: "Allowed Tools"
  welcome-message-choose: "Welcome, {player}! Choose your profession using"
  welcome-message-professions: "See available professions with"
  profession-already-selected: "You have already selected a profession: {profession}."
  invalid-profession: "The profession '{profession}' does not exist."
  profession-selected: "You are now a {profession}!"
  profession-reset: "Your {profession} profession has been reset."
  cannot-use-tool: "You cannot use this tool with your current profession."
  no-profession: "You need to choose a profession!"

default:
  allowed-tools:
    - "WOODEN_PICKAXE"
    - "WOODEN_SHOVEL"
    - "WOODEN_AXE"
    - "WOODEN_HOE"
    - "WOODEN_SWORD"

professions:
  miner:
    display-name: "Miner"
    description: "Masters of the underground, extracting precious ores and minerals"
    allowed-tools:
      - "NETHERITE_PICKAXE"
      - "DIAMOND_PICKAXE"
      - "IRON_PICKAXE"
      - "STONE_PICKAXE"
      - "WOODEN_PICKAXE"
  lumberjack:
    display-name: "Lumberjack"
    description: "Woodcutters who fell trees and harvest timber"
    allowed-tools:
      - "NETHERITE_AXE"
      - "DIAMOND_AXE"
      - "IRON_AXE"
      - "STONE_AXE"
      - "WOODEN_AXE"
  farmer:
    display-name: "Farmer"
    description: "Cultivators of the land, growing crops and raising livestock"
    allowed-tools:
      - "NETHERITE_HOE"
      - "DIAMOND_HOE"
      - "IRON_HOE"
      - "STONE_HOE"
      - "WOODEN_HOE"
  warrior:
    display-name: "Warrior"
    description: "Brave fighters who protect and defend against threats"
    allowed-tools:
      - "NETHERITE_SWORD"
      - "DIAMOND_SWORD"
      - "IRON_SWORD"
      - "STONE_SWORD"
      - "WOODEN_SWORD"
