settings:
  message-prefix: "&6[Profession]&r "
  debug-mode: false

messages:
  no-permission: "&cYou do not have permission to use this command."
  no-profession: "&cYou must select a profession first."
  profession-assigned: "&aYou have been assigned the profession: &e{profession}&a."
  profession-removed: "&aYour profession has been removed."
  invalid-profession: "&cThe specified profession does not exist."
  current-profession: "&aYour current profession is: &e{profession}&a."

# Define default allowed tools for all professions
default:
  allowed-tools:
    - "WOODEN_PICKAXE"
    - "WOODEN_SHOVEL"
    - "WOODEN_AXE"
    - "WOODEN_HOE"

# Define professions here
professions:
  miner:
    display-name: "Miner"
    description: "Masters of the underground, extracting precious ores and minerals"
    allowed-tools:
      - "NETHERITE_PICKAXE"
      - "DIAMOND_PICKAXE"
      - "IRON_PICKAXE"
      - "STONE_PICKAXE"
  lumberjack:
    display-name: "Lumberjack"
    description: "Woodcutters who fell trees and harvest timber"
    allowed-tools:
      - "NETHERITE_AXE"
      - "DIAMOND_AXE"
      - "IRON_AXE"
      - "STONE_AXE"




