name: UniqueProfessions
version: '${project.version}}'
main: dev.kalbarczyk.uniqueProfessions.UniqueProfessions
api-version: '1.21'
authors: [ Tepeshini(Kalbarczyk.dev) ]
description: A Minecraft plugin that adds unique professions for players.

commands:
  profession:
    description: Main profession command
    usage: /profession [choose|info|list|reset]
    aliases: [ prof, job ]

  professionadmin:
    description: Admin commands for managing professions
    usage: /professionadmin [set|setlevel|addxp|reset|reload|info]
    aliases: [ profadmin, padmin ]
    permission: profession.admin

permissions:
  profession.admin:
    description: Allows access to admin commands
    default: op

  profession.bypass:
    description: Bypass all profession restrictions
    default: op

  profession.use:
    description: Allows using the profession system
    default: true