name: UniqueProfessions
version: '${project.version}}'
main: dev.kalbarczyk.uniqueProfessions.UniqueProfessions
api-version: '1.21'
authors: [ Tepeshini(Kalbarczyk.dev) ]
description: A Minecraft plugin that adds unique professions for players.

commands:
  profession:
    description: Main profession command
    usage: /unique-profession [choose|info|list|reset]
    aliases: [ up, prof, profession ]

permissions:
  unique-profession.bypass:
    description: Bypass all profession restrictions
    default: op

  unique-profession.use:
    description: Allows using the profession system
    default: true